services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL="${PGADMIN_EMAIL}"
      - PGADMIN_DEFAULT_PASSWORD="${PGADMIN_PASSWORD}"
    ports:
      - "${PGADMIN_PORT}:80"
